services:
  ids-app:
    build: .
    image: ids-app-image
    container_name: ids-application
    restart: unless-stopped
    environment:
      SPRING_APPLICATION_NAME: ids
      SPRING_DATASOURCE_URL: jdbc:postgresql://89.40.142.92:5432/${POSTGRES_DB}?
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      # Add Java 21 specific optimizations
      JAVA_TOOL_OPTIONS: "-XX:+UseZGC -Xmx512m"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3